version: "3.7"


services:
  postgres:
    image: postgres:14.3-alpine3.15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: piracanjuba
      POSTGRES_DB: patrimoniomanager
    ports:
      - 5432:5432